<!DOCTYPE HTML>
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Noa Samarelli</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="assets/css/main.css" />
		<noscript><link rel="stylesheet" href="assets/css/noscript.css" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<a href="index.html" class="logo"><strong>N S</strong></a>
						<nav>
							<a href="#menu">Menu</a>
						</nav>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<ul class="links">
							<li><a href="index.html">Home</a></li>
							<li><a href="resume.html">Resume</a></li>
							<li><a href="contact.html">Contact</a></li>
						</ul>
					</nav>

				<!-- Banner -->
				<!-- Note: The "styleN" class below should match that of the header element. -->
				<section id="banner" class="style2">
					<div class="inner">
						<span class="image">
							<img src="images/pic07.jpg" alt="" />
						</span>
						<header class="major">
							<h1>Digital Manufacturing</h1>
						</header>
						<div class="content">
							<p>Manufacturing by software<br />
							Class taught by Professor Hod Lipson</p>
						</div>
					</div>
				</section>


				<!-- Main -->
					<div id="main" class="alt">

						<!-- One -->
							<section id="one">
								<div class="inner">
									<header class="major">
										<h2>Generative Design</h2>
									</header>
									<p>Creating physical objects directly from a software blueprint.</p>
						
						<!-- Two-->
							<section id="two">
								<section>
								</a>
								<div class="content">
									<div class="inner">
										<header class="major">
								<h3><a href="https://www.youtube.com/watch?v=JW6lLwNDB0E" target="_blank"><u><i>Lampshade Lattice</i></u></a></h3>
							</header>
							<p>The goal of this project was to perform generative design for 3D printing: design and print a lamp shade made entirely of a 3D printed lattice. The lampshade needed to accomodate a LED tea-light, and be stable on a flat surface. I wrote a program on OpenSCAD that generated geometry procedurally. Then exported its STL file, imported it on a 3D printer slicer and 3D printed a model.<br>
							<h4>Check <a href="https://www.youtube.com/watch?v=JW6lLwNDB0E" target="_blank"><u><i>THIS</u></i></a> video out!</h4>
							</p>
							<span class="image main"><img src="images/lattice1.png" alt="" /></span>
							<p><h4>Steps and Algorithm Description</h4>

								<h5>Design A</h5>
								
								Design A was coded in Python using the Openpyscad library. A sphere with a wall thickness of 3mm was created by extruding a sphere with radius of 52 mm and removing one with a radius of 49 mm. To create a flat surface and a clean cut to the wall of the model, a sphere (y) was removed in a negative translation along the z axis of 25 mm. To create the base the tea-light holder along the sphere cut, a base cylinder with height 2 mm and radius 43 mm and a one of height 10 mm and radius 22 mm were extruded. A third cylinder with height 11 mm (to assure a clean cut on OpenSCAD) and radius of 20 mm was removed. 
								<br><br>
								The holes on the sphere were created with 2 for loops controlling the angles θ (o) and φ (q) and translation along the sphere using the spherical Caertesian coordinates listed below.
								<br><br>
								x=r sin⁡θ cos⁡φ<br>
								x=r sin⁡θ sin⁡φ<br>
								x=r cos⁡θ
								<br><br>
								These were then removed from the sphere. A final cylinder was removed to create the top hole that allows a better visual of the inside of the design. Number of elements: 572.
								<br><br>
								The initial design of Model A had originally a support system at the base of the sphere generated by the following code by introducing a cubic hollow line at the translation coordinates of x= -43.5, y=5 and z=1.5 and then add a 2 set of cylinders with a x rotation of ~45° and y rotation of 25° by the means of a loop around the sphere:
								<br><br>
								<pre><code>c7=ops.Cube([5,5,5]).translate([-43,5,1.5])
u= ops.Union()
for i in range (180):
	c8=c7.rotate([0,0,2*i])
	u.append(c8)
									
c9=ops.Cylinder(h=7*math.sqrt(2),r=0.6).rotate([45,25,0]).translate([39.5,0,1])
c10=ops.Cylinder(h=7*math.sqrt(2),r=0.6).rotate([-45,25,0]).translate([39.5,0,1])
c11=c9+c10
								
d=ops.Union()
for i in range (20):
c12=c11.rotate([0,0,18*i])
d.append(c12)
</code></pre>
								
								As shown in the initial report in the Appendix, the design met all the requirements to be 3D printed. The print was set up on the Ultimaker 5 to be print with PLA and water-soluble material (Figure 3) so that there would be no risk in breaking the base with cylinders with a radius of just 0.6 mm. However, after 2 hours in warm water, the PLA softened and the base broke. The base was, thus, removed and the sphere was translated back by 30 mm in the z axis. 
								
								The rendering time of this model was 4 hours an average. The long time was sourced back to the scale function. It was, thus, removed and a new set of calculations were computed in order to get the model to fit in the Bounding Box. Number of Elements of Initia Design A: 914.

								<br>
								<br>
								
								<h5>Design B</h5>
								
								Design B was coded on OpenSCAD. The base was coded to have a flat surface by generating a cylinder and then adding rounded sides by creating a 2D circle and then rotating to create torus-shaped sides. 
								
								In order to fit a teacup, light a cylinder extrusion was removed from one with a bigger radius.
								
								2 for loops were used to create the walls of the design, using a positive and negative rotation to create the rhombus grid: the cylinders were created using a linear extrusion of a circle with radius of 2 mm. Number of elements :42.
								</p>
							<div class="box alt">
							<div class="row gtr-50 gtr-uniform">
							<div class="col-20"><span class="image fit"><img src="images/lattice5.png" alt="" /></span></div>
							
							<a href="#" class="image">
								<img src="images/lampshade.gif" alt="" data-position="center" width="400" height="700"/>
							</a>
							</section>
								</div>
							</section>

					<!-- Contact -->
					<section id="contact">
						<div class="inner">
						</div>
					</section>
	
				<!-- Footer -->
					<footer id="footer">
						<div class="inner">
							<ul class="icons">
								<li><a href="mailto:noa.samarelli@columbia.edu" target="_blank" class="icon solid alt fa-envelope"><span class="label">Mail</span></a></li>
								<li><a href="https://www.linkedin.com/in/noasamarelli/" target="_blank" class="icon brands alt fa-linkedin-in"><span class="label">LinkedIn</span></a></li>
								<li><a href="https://github.com/noasamarelli" target="_blank" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>
							</ul>
							<ul class="copyright">
								<li>&copy; Untitled</li></li>
							</ul>
						</div>
					</footer>
	
			</div>
	
		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/browser.min.js"></script>
			<script src="assets/js/breakpoints.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>
	
	</body>
	</html>